package persistance.entities;
// Generated 1 avr. 2021 15:30:22 by Hibernate Tools 5.4.14.Final



/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private Integer code;
	private String nom;
	private Double moyenne;

	public Etudiant() {
	}

	public Etudiant(Integer code) {
		this.code = code;
	}

	public Etudiant(Integer code, String nom, Double moyenne) {
		this.code = code;
		this.nom = nom;
		this.moyenne = moyenne;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Double getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(Double moyenne) {
		this.moyenne = moyenne;
	}

}
